### ISSUE TITLE
What changed in the April update?

### ISSUE THREAD

**Issue by dandv** [asafh/chrome-tabcounter#2]
The [Chrome web store shows an April 21, 2016 update](https://chrome.google.com/webstore/detail/tab-counter/feeoiklfggbaibpdhkkngbpkppdmcjal), but the last commit here is from 3 years ago.

**Comment by asafh** [comment]
There was no code change, but update to the information in the Chrome Web Store due to some policy changes:

> Dear Developer,
> 
> We recently announced a policy change aimed at enhancing user transparency and choice over how users’ personal data is handled. Please review the additional language on Developer Program Policy under the section “User Data Privacy.”

Therefore I had a couple fields to edit there.
