### ISSUE TITLE
ADD support for displaying current window tab count

### ISSUE THREAD

**Issue by allanlaal** [asafh/chrome-tabcounter#5]
discussed in https://github.com/asafh/chrome-tabcounter/issues/3#issuecomment-294011759

**Comment by asafh** [comment]
Unfortunately that's pretty awkward to do at the moment.  
Firstly to know the number you have to keep track of which tab id belongs to which window id while they are updated (or as a workaround just query all tabs every time a tab is opened/closed/updated which isn't so nice of the extension).  
Either solution, displaying that number will still be very inconvenient as chrome allows you to update the extension's browserAction (the button) either globally or for a specific tab, which means we'd still have to do tab-window ownership bookkeeping so we can set the information for it (either upon number change or when it becomes the selected tab in the window).

I'll keep it in mind but at least for now I'll hold on doing this - though you're welcome to open a PR.

**Comment by allanlaal** [comment]
nah, this isn't as critical as an accurate global tab count
